#!/usr/bin/env bash

# Git Tree view
# https://dev.to/drews256/i-love-git-log-off
alias gtree='git log --graph --abbrev-commit --decorate --date=relative --format=format:'\''%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'\'' --all'

# Show pretty git log
alias git_log_pretty="git log --pretty=oneline --abbrev-commit --graph --decorate --all"

# Show git diff for untracked files only
alias git_diff_untracked="less $(git ls-files --others --exclude-standard)"

# Show git diff for staged files only
alias git_diff_cached="git diff --cached"
