#!/usr/bin/env bash

# Git Tree view
# https://dev.to/drews256/i-love-git-log-off
alias gtree='git log --graph --abbrev-commit --decorate --date=relative --format=format:'\''%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'\'' --all'

# Show pretty git log
alias git_log_pretty="git log --pretty=oneline --abbrev-commit --graph --decorate --all"

# Show git diff for untracked files only
alias git_diff_untracked="less $(git ls-files --others --exclude-standard)"

# Show git diff for staged files only
alias git_diff_cached="git diff --cached"

# Get recent branches (ones on which you have worked in your local)
# Credit https://stackoverflow.com/questions/5188320/how-can-i-get-a-list-of-git-branches-ordered-by-most-recent-commit
#alias git_recent="git branch -v --sort=committerdate"
alias git_recent="git for-each-ref --sort=-committerdate refs/heads/ --format='%(committerdate:short) %(authorname) %(refname:short)'"
