#!/usr/bin/env bash

sudo systemctl enable vnstat
sudo systemctl enable gdm

# Let NetworkManager handle network and not dhcpcd
sudo systemctl disable dhcpcd
sudo systemctl enable NetworkManager

sudo groupadd docker
sudo usermod -aG docker ${USER}
# sudo systemctl enable docker

