#!/usr/bin/env bash

# Default editor as vim
export EDITOR="vim"

# Set bash history to unlimited
# https://stackoverflow.com/a/19533853

# Setting unlimited history
# https://stackoverflow.com/questions/9457233/unlimited-bash-history
HISTSIZE=-1
HISTFILESIZE=-1

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '


# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion