#!/usr/bin/env bash

mkdir -p ~/.pyenv
cd ~
git clone https://github.com/pyenv/pyenv.git .pyenv
cd .pyenv
PYENV_DIR="$(pwd)"
echo "export PYENV_ROOT=\"$PYENV_DIR\"" >> ~/.zshenv
echo "export PATH=\"$PYENV_DIR/bin:$PATH\"" >> ~/.zshenv
echo 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshenv
git clone https://github.com/pyenv/pyenv-virtualenv.git ./plugins/pyenv-virtualenv
echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshenv
#exec "$SHELL"