#!/usr/bin/env bash

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
echo "plugins=(
    archlinux
    git
    history-substring-search
    colored-man-pages
    zsh-autosuggestions
    zsh-syntax-highlighting
)
" >> ~/.zshrc
# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
echo "ZSH_THEME=\"robbyrussell\"" >> ~/.zshrc

# make zsh default
sudo usermod -s /bin/zsh $(whoami)
# for mac
# sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -s $(which zsh)